spring:
    datasource:
            type: com.zaxxer.hikari.HikariDataSource
            url: jdbc:mysql://192.168.1.9:3360/?useUnicode=true&characterEncoding=utf8&useSSL=false
            username:
            password:
            hikari:
                data-source-properties:
                    cachePrepStmts: true
                    prepStmtCacheSize: 250
                    prepStmtCacheSqlLimit: 2048
                    useServerPrepStmts: true
                driver-class-name: com.mysql.jdbc.Driver
    jooq:
        sql-dialect: mysql


application:
    database-to-export: riskdbtest
    ignored-table-names:
        - databasechangelog
        - databasechangeloglock
    export:
        path: ./my-project-jdl.jh
        type: jdl
